### ISSUE TITLE
Package is very out of date

### ISSUE THREAD

**Issue by freddyaboulton** [conda-forge/gradio-feedstock#19]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hi!

This package is very out of date and is causing trouble for people installing gradio via conda. https://github.com/gradio-app/gradio/issues/4974#issuecomment-1687861604

Can you please update the package (or remove it so that people can't install via conda and expect to get an up to date and working vevrsion)?

Thank you!

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by Sclare87** [comment]
Sorry for the long wait for an update.
I got the gradio-client to be added to conda-forge and so a was finally able to update gradio to the newest version.
